FIX: module stage should be rewrite

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -65,7 +65,8 @@ build:
       ./configure \
       --add-dynamic-module=.. \
       --with-ld-opt="-Wl,-rpath,/usr/local/lib" \
-      --with-compat
+      --with-compat \
+      --with-debug
     - make modules
 
   artifacts:
@@ -92,7 +93,7 @@ test:
     - |
       if [ ! -f model.onnx.tar.gz ]; then
         curl -L -o model.onnx.tar.gz \
-        https://release-assets.githubusercontent.com/github-production-release-asset/1105843404/7048791a-4122-490c-8209-52716a6aacb9?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-04-17T00%3A11%3A16Z&rscd=attachment%3B+filename%3Dmodel.onnx.tar.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-04-16T23%3A10%3A44Z&ske=2026-04-17T00%3A11%3A16Z&sks=b&skv=2018-11-09&sig=alOHwXMI4TU9WOfiabnqjnTUJfnlr5A%2FTlHAlAkOSrY%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NjM4MjAxMiwibmJmIjoxNzc2MzgxNzEyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.KpeRqm1eJFcwbAmEsjIIb4ABmfyvPySOvW72i1Vp0Xw&response-content-disposition=attachment%3B%20filename%3Dmodel.onnx.tar.gz&response-content-type=application%2Foctet-stream
+        https://github.com/Sh1roKur0/ngx_http_ml_ddos_module/releases/download/Release/model.onnx.tar.gz
         fi
     - tar xf model.onnx.tar.gz
     - mv model.onnx /etc/nginx/model.onnx
@@ -114,9 +115,21 @@ test:
           server {
               listen 8080;
 
-              location /test {
+              location /ml {
                   ml_ddos on;
-                  return 200 "OK\n";
+                  default_type text/plain;
+                  return 200 "ML\n";
+              }
+
+              location /no_ml {
+                  ml_ddos off;
+                  default_type text/plain;
+                  return 200 "NO_ML\n";
+              }
+
+              location /default {
+                  default_type text/plain;
+                  return 200 "Default\n";
               }
           }
       }
@@ -128,9 +141,27 @@ test:
 
     - |
       for i in $(seq 1 20); do
-        curl -s http://127.0.0.1:8080/test && break
+        curl -s http://127.0.0.1:8080/default && break
         sleep 1
       done
-    - curl -i http://127.0.0.1:8080/test
+
+    - >
+      curl -s -D - http://127.0.0.1:80/ml -o /dev/null | grep -q "X-HTTP-ML-DDOS: Enabled" && echo "PASS: ml"
+
+    - |
+      if curl -s -D - http://127.0.0.1:80/no_ml -o /dev/null | grep -q "X-HTTP-ML-DDOS: Enabled"; then
+        echo "FAIL: header should not exist"
+        exit 1
+      else
+        echo "PASS: no_ml"
+      fi
+
+    - |
+      if curl -s -D - http://127.0.0.1:80/default -o /dev/null | grep -q "X-HTTP-ML-DDOS: Enabled"; then
+        echo "FAIL: ml_ddos off by default"
+        exit 1
+      else
+      echo "PASS: default"
+      fi
 
     - nginx -s stop
